### ISSUE TITLE
Feature: Settings Page

### ISSUE THREAD

**Issue by trdillon** [trdillon/CurrencyConverter#2]
# Epic Task
Add settings page

## Epic Description
This feature will add a settings page, accessed by the tool bar icon, that will allow the user to manage their API keys, change the color scheme, and more.

## List of Tasks

- [x] #3 Create SettingsView.fxml

- [x] #4 Create load/save functions for config.properties

- [x] #5 Add function to manage API keys

- [x] #6 Add function to change color scheme

- [x] #7 Write tests for settings functions
